### PR TITLE
Adding World Explorations

### PR DESCRIPTION
**Pull request by wiebecommajonas**
I added the new collection World Explorations to the json files.

### CODE REVIEW

**Comment by atdr** [comment]
Hey @wiebecommajonas, thanks for the PR! One thing: looks like the spaces in the range/capsule names got removed in `data.min.json`—could you bring them back to be consistent with the previous version? The names are used verbatim in the Shortcut so the spaces are important for readability :)

**Comment by wiebecommajonas** [comment]
Yes of course. I made a mistake when converting the data. Should be fixed now.

**Review by atdr — CHANGES_REQUESTED** [review]
One last thing—could you [remove `.DS_Store`](https://stackoverflow.com/a/19299889) from the PR?

I'll drop a `.gitignore` in the repo right after so it doesn't happen again (I should have done that sooner, sorry)

**Comment by wiebecommajonas** [comment]
Damn, I'm having trouble with this whole Pull Request thing. But it should be okay now?

**Comment by atdr** [comment]
That's great, thanks!

I've published a new [tag `v1.1`](https://github.com/atdr/capsule-caffeine/releases/tag/v1.1) so you can update the Shortcut to point to the new JSON (or you can point it at your own fork if you'd prefer 😉)

IMG_0466

**Pull request merged**
